# GitHub Nodejs CI
name: lerna

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: lerna install, build, and test
        run: |
          npm install lerna -g
          yarn install

        env:
          CI: ''
      - run: lerna link
      - run: lerna exec yarn install
